include:
  - board: seeeduino_xiao_ble
    shield: totem_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: totem_right rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: totem_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: settings_reset